### ISSUE TITLE
Does not seem to scan IP based URLs

### ISSUE THREAD

**Issue by Johnng007** [Anteste/WebMap#10]
Nice Tool but doesnt seem to scan IP based URLs
like: http://10.12.1.23
`Traceback (most recent call last):
  File "/usr/local/bin/webmap", line 56, in <module>
    main()
  File "/usr/local/bin/webmap", line 48, in main
    conf.call_def(conf.full_scan)
  File "/home/kali/Desktop/TOOLS/WEB ATTACK/WebMap/conf/conf.py", line 80, in call_def
    func()
  File "/home/kali/Desktop/TOOLS/WEB ATTACK/WebMap/modules/fullscan.py", line 31, in full_scan
    full_ip = conf.socket.gethostbyname(full_host)
socket.gaierror: [Errno -2] Name or service not known
`

**Comment by Anteste** [comment]
You can download the new version of WebMap.
It's Solved ;)
